name: Playwright Tests

on:
  workflow_dispatch: # Enables manual triggering of the workflow
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Playwright browsers
      run: playwright install

    - name: Run tests
      run: pytest

    - name: Debugging List files for upload
      if: always()
      run: ls -R

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3.1.2 # Explicitly specify the latest version
      with:
        name: test-results
        path: |
          test-results/
          report.html
